server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userweb
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
  profiles:
    active: dev

common:
  hosts: "127.0.0.0" #Es地址
  port: 9601
  username: "zlw-es"


